name: a2c
gamma: 0.99
gae_lambda: 1.0
entropy_coef: 0.0
value_loss_coef: 0.5
max_grad_norm: 0.5
use_sde: false
sde_sample_freq: -1
normalize_advantage: false
# How many steps to advantage for calculating the sum of rewards
num_steps: 5
